spring:
  datasource:
    url: jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    platform: h2
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect